import { Player } from "../models";

export const dummyPlayers: Player[] = [
  {
    id: 26,
    name: "John Micks",
    preferred_position: "goalkeeper",
    skill: 13,
    matches_played: 0,
    goals_scored: 0,
    assists_made: 0,
    sell_price: 15,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 30,
    name: "Herman Stahl",
    preferred_position: "defender",
    skill: 15,
    matches_played: 0,
    goals_scored: 0,
    assists_made: 0,
    sell_price: 17,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 31,
    name: "Jon Reardon",
    preferred_position: "attacker",
    skill: 9,
    matches_played: 0,
    goals_scored: 0,
    assists_made: 0,
    sell_price: 11,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 32,
    name: "Michael Hunt",
    preferred_position: "defender",
    skill: 17,
    matches_played: 0,
    goals_scored: 0,
    assists_made: 0,
    sell_price: 19,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 33,
    name: "Gerardo Scott",
    preferred_position: "defender",
    skill: 12,
    matches_played: 0,
    goals_scored: 0,
    assists_made: 0,
    sell_price: 14,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 34,
    name: "Jorge Jerome",
    preferred_position: "attacker",
    skill: 15,
    matches_played: 0,
    goals_scored: 0,
    assists_made: 0,
    sell_price: 17,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 35,
    name: "Jack Hill",
    preferred_position: "defender",
    skill: 16,
    matches_played: 0,
    goals_scored: 0,
    assists_made: 0,
    sell_price: 18,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 15,
    name: "Joan Lewis",
    preferred_position: "defender",
    skill: 15,
    matches_played: 102,
    goals_scored: 17,
    assists_made: 2,
    sell_price: 17,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 14,
    name: "Billy Figueroa",
    preferred_position: "defender",
    skill: 25,
    matches_played: 102,
    goals_scored: 1,
    assists_made: 2,
    sell_price: 27,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 16,
    name: "William Lattimer",
    preferred_position: "attacker",
    skill: 23,
    matches_played: 102,
    goals_scored: 8,
    assists_made: 10,
    sell_price: 25,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 24,
    name: "Patrick Clark",
    preferred_position: "defender",
    skill: 14,
    matches_played: 102,
    goals_scored: 14,
    assists_made: 4,
    sell_price: 16,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
  {
    id: 25,
    name: "Steven Zafar",
    preferred_position: "attacker",
    skill: 16,
    matches_played: 102,
    goals_scored: 7,
    assists_made: 12,
    sell_price: 18,
    team: {
      id: 10,
      name: "new team",
      owner: 4,
    },
  },
];
